[versions]
agp = "8.13.1"
kotlin = "2.2.0"
coreKtx = "1.17.0"
splash = "1.0.1"
material = "1.13.0"
icons = "1.5.0"
composeBom = "2025.10.01"
composeLifeCycle = "2.8.5"
composeActivity = "1.11.0"
composeNavigation = "2.7.7"
koin = "3.5.3"
room = "2.7.2"
ksp = "2.2.0-2.0.2"
camera = "1.3.0"
exoplayer = "1.3.1"
workmanager = "2.8.1"
accompanist = "0.34.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splash" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
material3 = { group = "androidx.compose.material3", name = "material3" }
compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "icons" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeLifeCycle" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
camera-extension = { module = "androidx.camera:camera-extensions", version.ref = "camera" }
camera-video = { module = "androidx.camera:camera-video", version.ref = "camera" }
exoplayer-core = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer" }
exoplayer-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayer" }
workmanager = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

